### ISSUE TITLE
it didn't generate the password although  it's in the key words  !!!!!

### ISSUE THREAD

**Issue by minanagehsalalma** [tch1001/pwdlogy#2]
the password is Sahraamenashrafzakygirges0109261517201093116160
 the keywords that i have used 
sahraa
men
ashraf
zaky
girges
01093116160
01092615172
sahraamenashrafzakygirges
![image](https://user-images.githubusercontent.com/20546638/33516267-9f947bb2-d778-11e7-9c24-5f3bd85665cf.png)
![image](https://user-images.githubusercontent.com/20546638/33516268-a5b9f67a-d778-11e7-9950-fb836494f3f9.png)
i hadn't change the configuration or the settings 
@tch1001

**Comment by tch1001** [comment]
Hi, thanks for checking Pwdlogy out!!

I believe the "formats" section can solve your problem. In the https://github.com/tch1001/pwdlogy/blob/master/formats_default.conf default formats file, the abbreviation "kkk" does not exist. Hence, the generator will not ceeate passwords of the format <keyword><keyword><keyword>. In order for it to generate the <keyword><keyword><keyword> format, you would need to create your own formats file. I think you will find the "formats" section of the README.md useful. Good luck! Feel free to ask my any questions.

Yours sincerely,
tch1001

**Comment by minanagehsalalma** [comment]
thank you so much for the fast and friendly response
.. i had found it with this format Kkkkkkk 
![image](https://user-images.githubusercontent.com/20546638/33516654-1b7784c6-d77f-11e7-9e00-109b3098811f.png)
@tch1001
